### ISSUE TITLE
Any chance of switching to an Apache or MIT license?

### ISSUE THREAD

**Issue by kdykeman** [fazibear/colorize#59]
One interpretation of GPL 2.0 has made it so that I am discouraged from using this gem. The Apache and MIT licenses encourage using libraries with less copy-left implications. Any chance of shifting?

**Comment by dprater** [comment]
👍  Our company can't use GPL licensed software, and colorize is included in the Spinach gem, which we use heavily. If the colorize license can't be updated to something non-GPL/LGPL, we potentially have to remove spinach from our environment which we would very much like to avoid since we already have a significant amount of work done for spinach.

**Comment by dprater** [comment]
https://github.com/fazibear/colorize/issues/47 - already requested, never addressed.

**Comment by hamannp** [comment]
We're coming up on a year, and this is still an issue. It is becoming a blocker for us -- we will have to remove colorize from our product soon if this is not addressed. @fazibear Rails is often used for commercial projects. It comes with a more permissive license for that reason, and is why MIT, Apache, and the ruby license are the norm in the ruby ecosystem. Is it your goal to block commercial use? Can you provide some context and some of your reasoning?

**Comment by jhubert** [comment]
Experiencing the same issue. Any chance of making the switch or providing a commercial license option?

**Comment by vfonic** [comment]
There's another gem providing similar functionality that you can switch to:
https://github.com/sickill/rainbow

It's licensed under the MIT license and I've seen projects switching to it.
